# Generated by Django 4.2.9 on 2024-01-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_file', models.FileField(upload_to='file_upload/')),
            ],
        ),
    ]
